In [132]:
from pytrials.client import ClinicalTrials
import pandas as pd
import calendar
import time

# Loading to db
# importing os module for environment variables
import os
# importing necessary functions from dotenv library
from dotenv import load_dotenv 
# loading variables from .env file
load_dotenv() 
import psycopg2
from sqlalchemy import create_engine

In [11]:
# max_studies limit is 1000
ct = ClinicalTrials()
#results = ct.get_full_studies(search_expr="endometriosis", max_studies = 50)

Querying the date from 1870 to 1963, it seems like the first record or article in Clinical Trials is in 1900.
Specifically for my keywords the first instance is in 1948

1998 is when it hits it MAX PULLS

FIRST BLOCK: 1948 - 1998 (QUERY YEAR)
SECOND BLOCK 1999 - 2007 (QUERY MONTH)
THIRD BLOCK 2008 - 2026 (QUERY MONTH, but loop through keywords)

In [ ]:
#########################################################################################################################################################

In [111]:
search_terms1 = "(Abdominal cerclage OR Abnormal pap smears OR Abnormal uterine bleeding OR Alzheimer's disease OR Amenorrhea OR Amniocentesis OR Arthritis OR Asthma OR Bacterial vaginosis OR Bleeding disorders OR Breast cancer OR Cancers OR Celiac disease OR Cervical cancer OR Cervical insufficiency OR Cervicitis OR Cesarean section (C-section) OR Chorionic villus sampling OR Colposcopy OR Congenital abnormalities OR Continence OR Contraception (birth control) OR Cystoscopy OR Depression and anxiety OR Dilation and curettage (D and C) OR Dysmenorrhea OR Endometrial ablation OR Endometrial biopsy OR Endometrial cancer OR Endometriosis OR Epilepsy OR Family planning OR Female genital cutting OR Fertility preservation OR Fibroma OR Gallstone disease OR Genetic conditions OR Gentle cesarean section OR Gestational diabetes OR Gestational trophoblastic disease OR Graves' disease OR Gynecologic cancer OR Gynecologic specialty care OR Gynecologic well-woman care OR Gynecological surgery OR Heart disease OR Heavy menstrual cycles OR High-risk pregnancy OR HIV OR HPV OR In-vitro fertilization OR Infertility OR Integrative medicine OR Interstitial cystitis OR Irritable bowel syndrome (IBS) OR Laparoscopic hysterectomy OR Laparoscopy OR Loop electrosurgical excision procedure (LEEP) OR Lupus OR Menopause OR Menorrhagia OR Menstrual conditions OR Miscarriage OR Morning sickness OR Multiple sclerosis OR Myomectomy OR Osteoarthritis OR Osteoporosis OR Ovarian cancer OR Ovarian cysts OR Ovarian fibroma OR Overactive bladder OR Pancreatic cystic neoplasm OR Pap test OR Pelvic inflammatory disease (PID) OR Pelvic organ prolapse OR Pelvic pain OR Pelvic ultrasound OR Perimenopause OR Placenta accreta OR Placenta previa OR Polycystic ovary syndrome (PCOS) OR Postpartum depression OR Preconception planning OR Pregnancy OR Pregnancy complications OR Pregnancy, first trimester OR Pregnancy, multiples OR Pregnancy, second trimester OR Pregnancy, third trimester OR Premenstrual dysphoric disorder (PMDD) OR Premenstrual syndrome (PMS) OR Prenatal care OR Prenatal genetic screening OR Preterm birth OR Primary care for women OR Recurrent pregnancy loss OR Rheumatoid arthritis OR Robotic hysterectomy OR Robotic myomectomy OR Sexually transmitted diseases (STDs) OR Sleep disorders OR Small vessel disease OR Sports injuries OR STIs OR Stress urinary incontinence OR Stroke OR Thyroid disease OR Transgender care OR Tubal ligation OR Turner syndrome OR Type I autoimmune hepatitis OR Ultrasound OR Urinary incontinence OR Urinary tract infections (UTIs) OR Uterine and vaginal prolapse OR Uterine fibroids OR Vaginal birth after cesarean section OR Vaginal cancer OR Vaginitis OR Vulvar cancer OR Vulvar dysplasia OR Vulvitis OR Yeast infection)"
fields1 = ct.get_study_fields(
    search_expr=f"{search_terms1} AND AREA[StartDate]RANGE[1948-01-01, 1998-12-31]",
    fields = ["NCT Number", 
              "Study Title", 
              "Study Status",
              "Brief Summary",
              "Conditions",
              "Primary Outcome Measures",
              "Sponsor",
              "Collaborators",
              "Sex",
              "Age",
              "Enrollment",
              "Study Type",
              "Funder Type",
              "Start Date",
              "Completion Date"],
    max_studies = 1000,
    fmt = "csv"
)

# conver to dataframe
df1 = pd.DataFrame.from_records(fields1[1:], columns = fields1[0])
#print(df1.info())
print(df1.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   NCT Number                1000 non-null   str
 1   Study Title               1000 non-null   str
 2   Study Status              1000 non-null   str
 3   Brief Summary             1000 non-null   str
 4   Conditions                1000 non-null   str
 5   Primary Outcome Measures  1000 non-null   str
 6   Sponsor                   1000 non-null   str
 7   Collaborators             1000 non-null   str
 8   Sex                       1000 non-null   str
 9   Age                       1000 non-null   str
 10  Enrollment                1000 non-null   str
 11  Funder Type               1000 non-null   str
 12  Study Type                1000 non-null   str
 13  Start Date                1000 non-null   str
 14  Completion Date           1000 non-null   str
dtypes: str(15)
memory usage: 1.0 MB
None

In [ ]:
### CHECK WHEN A MONTH WILL HIT 1000
# 1998 - 2027

search_terms = "(Abdominal cerclage OR Abnormal pap smears OR Abnormal uterine bleeding OR Alzheimer's disease OR Amenorrhea OR Amniocentesis OR Arthritis OR Asthma OR Bacterial vaginosis OR Bleeding disorders OR Breast cancer OR Cancers OR Celiac disease OR Cervical cancer OR Cervical insufficiency OR Cervicitis OR Cesarean section (C-section) OR Chorionic villus sampling OR Colposcopy OR Congenital abnormalities OR Continence OR Contraception (birth control) OR Cystoscopy OR Depression and anxiety OR Dilation and curettage (D and C) OR Dysmenorrhea OR Endometrial ablation OR Endometrial biopsy OR Endometrial cancer OR Endometriosis OR Epilepsy OR Family planning OR Female genital cutting OR Fertility preservation OR Fibroma OR Gallstone disease OR Genetic conditions OR Gentle cesarean section OR Gestational diabetes OR Gestational trophoblastic disease OR Graves' disease OR Gynecologic cancer OR Gynecologic specialty care OR Gynecologic well-woman care OR Gynecological surgery OR Heart disease OR Heavy menstrual cycles OR High-risk pregnancy OR HIV OR HPV OR In-vitro fertilization OR Infertility OR Integrative medicine OR Interstitial cystitis OR Irritable bowel syndrome (IBS) OR Laparoscopic hysterectomy OR Laparoscopy OR Loop electrosurgical excision procedure (LEEP) OR Lupus OR Menopause OR Menorrhagia OR Menstrual conditions OR Miscarriage OR Morning sickness OR Multiple sclerosis OR Myomectomy OR Osteoarthritis OR Osteoporosis OR Ovarian cancer OR Ovarian cysts OR Ovarian fibroma OR Overactive bladder OR Pancreatic cystic neoplasm OR Pap test OR Pelvic inflammatory disease (PID) OR Pelvic organ prolapse OR Pelvic pain OR Pelvic ultrasound OR Perimenopause OR Placenta accreta OR Placenta previa OR Polycystic ovary syndrome (PCOS) OR Postpartum depression OR Preconception planning OR Pregnancy OR Pregnancy complications OR Pregnancy, first trimester OR Pregnancy, multiples OR Pregnancy, second trimester OR Pregnancy, third trimester OR Premenstrual dysphoric disorder (PMDD) OR Premenstrual syndrome (PMS) OR Prenatal care OR Prenatal genetic screening OR Preterm birth OR Primary care for women OR Recurrent pregnancy loss OR Rheumatoid arthritis OR Robotic hysterectomy OR Robotic myomectomy OR Sexually transmitted diseases (STDs) OR Sleep disorders OR Small vessel disease OR Sports injuries OR STIs OR Stress urinary incontinence OR Stroke OR Thyroid disease OR Transgender care OR Tubal ligation OR Turner syndrome OR Type I autoimmune hepatitis OR Ultrasound OR Urinary incontinence OR Urinary tract infections (UTIs) OR Uterine and vaginal prolapse OR Uterine fibroids OR Vaginal birth after cesarean section OR Vaginal cancer OR Vaginitis OR Vulvar cancer OR Vulvar dysplasia OR Vulvitis OR Yeast infection)"

for year in range(1998, 2027):
    for month in range(1, 13):
        last_day = calendar.monthrange(year, month)[1]
        start_str = f"{year}-{month:02d}-01" # {month:02d} formats the month to MM because clinical trials is strict
        end_str = f"{year}-{month:02d}-{last_day:02d}"
        
        search_expr = f"{search_terms} AND AREA[StartDate]RANGE[{start_str}, {end_str}]"

        try: 
            data = ct.get_study_fields(
                search_expr=search_expr,
                fields=["NCT Number"],
                max_studies = 1000,
                fmt = "csv"
            )
            
            if data and len(data) > 0:
                studies_number = len(data) - 1
            else:
                studies_number = 0

            print(f"{year}-{month:02d}: Found {studies_number} studies")

        except Exception as e:
            print(f"Query error for {year}-{month:02d}: {e}")

        time.sleep(3)

# Found that 2007 is the first year that a month hit 1000 studies

In [ ]:
#########################################################################################################################################################
# FIRST BLOCK: 1948 - 1998

In [120]:
search_terms = "(Abdominal cerclage OR Abnormal pap smears OR Abnormal uterine bleeding OR Alzheimer's disease OR Amenorrhea OR Amniocentesis OR Arthritis OR Asthma OR Bacterial vaginosis OR Bleeding disorders OR Breast cancer OR Cancers OR Celiac disease OR Cervical cancer OR Cervical insufficiency OR Cervicitis OR Cesarean section (C-section) OR Chorionic villus sampling OR Colposcopy OR Congenital abnormalities OR Continence OR Contraception (birth control) OR Cystoscopy OR Depression and anxiety OR Dilation and curettage (D and C) OR Dysmenorrhea OR Endometrial ablation OR Endometrial biopsy OR Endometrial cancer OR Endometriosis OR Epilepsy OR Family planning OR Female genital cutting OR Fertility preservation OR Fibroma OR Gallstone disease OR Genetic conditions OR Gentle cesarean section OR Gestational diabetes OR Gestational trophoblastic disease OR Graves' disease OR Gynecologic cancer OR Gynecologic specialty care OR Gynecologic well-woman care OR Gynecological surgery OR Heart disease OR Heavy menstrual cycles OR High-risk pregnancy OR HIV OR HPV OR In-vitro fertilization OR Infertility OR Integrative medicine OR Interstitial cystitis OR Irritable bowel syndrome (IBS) OR Laparoscopic hysterectomy OR Laparoscopy OR Loop electrosurgical excision procedure (LEEP) OR Lupus OR Menopause OR Menorrhagia OR Menstrual conditions OR Miscarriage OR Morning sickness OR Multiple sclerosis OR Myomectomy OR Osteoarthritis OR Osteoporosis OR Ovarian cancer OR Ovarian cysts OR Ovarian fibroma OR Overactive bladder OR Pancreatic cystic neoplasm OR Pap test OR Pelvic inflammatory disease (PID) OR Pelvic organ prolapse OR Pelvic pain OR Pelvic ultrasound OR Perimenopause OR Placenta accreta OR Placenta previa OR Polycystic ovary syndrome (PCOS) OR Postpartum depression OR Preconception planning OR Pregnancy OR Pregnancy complications OR Pregnancy, first trimester OR Pregnancy, multiples OR Pregnancy, second trimester OR Pregnancy, third trimester OR Premenstrual dysphoric disorder (PMDD) OR Premenstrual syndrome (PMS) OR Prenatal care OR Prenatal genetic screening OR Preterm birth OR Primary care for women OR Recurrent pregnancy loss OR Rheumatoid arthritis OR Robotic hysterectomy OR Robotic myomectomy OR Sexually transmitted diseases (STDs) OR Sleep disorders OR Small vessel disease OR Sports injuries OR STIs OR Stress urinary incontinence OR Stroke OR Thyroid disease OR Transgender care OR Tubal ligation OR Turner syndrome OR Type I autoimmune hepatitis OR Ultrasound OR Urinary incontinence OR Urinary tract infections (UTIs) OR Uterine and vaginal prolapse OR Uterine fibroids OR Vaginal birth after cesarean section OR Vaginal cancer OR Vaginitis OR Vulvar cancer OR Vulvar dysplasia OR Vulvitis OR Yeast infection)"
target_fields =["NCT Number", "Study Title", "Study Status", "Brief Summary", "Conditions", "Primary Outcome Measures",
                "Sponsor", "Collaborators", "Sex", "Age", "Enrollment", "Study Type", "Funder Type", "Start Date", "Completion Date"]

dfs_list = []

for year in range(1948, 1999):
    start_str = f"{year}-01-01"
    end_str = f"{year}-12-31"
    year_query = f"{search_terms} AND AREA[StartDate]RANGE[{start_str}, {end_str}]"

    try:
        fields = ct.get_study_fields(search_expr=year_query, fields=target_fields,max_studies=1000,fmt="csv")
        
        if fields and len(fields) > 1:
            df = pd.DataFrame.from_records(fields[1:], columns=fields[0])
            dfs_list.append(df)

            studies_number = len(df)
            print(f"Year {year}: Found {studies_number} studies")

        else:
            print(f"Year {year}: No studies found.")

    except Exception as e:
        print(f"Error querying Year {year}: {e}")

    time.sleep(3)

if dfs_list:
    final_df = pd.concat(dfs_list, ignore_index = True)
else:
    print("No data collected")
    final_df = pd.DataFrame(columns=target_fields)
    

# conver to dataframe
#df = pd.DataFrame.from_records(fields[1:], columns = fields[0])
#print(df.info())

Year 1948: Found 1 studies
Year 1949: No studies found.
Year 1950: No studies found.
Year 1951: No studies found.
Year 1952: No studies found.
Year 1953: No studies found.
Year 1954: No studies found.
Year 1955: No studies found.
Year 1956: No studies found.
Year 1957: Found 1 studies
Year 1958: Found 1 studies
Year 1959: No studies found.
Year 1960: No studies found.
Year 1961: No studies found.
Year 1962: No studies found.
Year 1963: Found 1 studies
Year 1964: No studies found.
Year 1965: Found 3 studies
Year 1966: Found 3 studies
Year 1967: Found 1 studies
Year 1968: Found 1 studies
Year 1969: Found 2 studies
Year 1970: Found 1 studies
Year 1971: Found 7 studies
Year 1972: Found 6 studies
Year 1973: Found 6 studies
Year 1974: Found 2 studies
Year 1975: Found 4 studies
Year 1976: Found 14 studies
Year 1977: Found 22 studies
Year 1978: Found 18 studies
Year 1979: Found 12 studies
Year 1980: Found 17 studies
Year 1981: Found 11 studies
Year 1982: Found 12 studies
Year 1983: Found 31 studies
Year 1984: Found 36 studies
Year 1985: Found 37 studies
Year 1986: Found 48 studies
Year 1987: Found 54 studies
Year 1988: Found 86 studies
Year 1989: Found 75 studies
Year 1990: Found 109 studies
Year 1991: Found 146 studies
Year 1992: Found 183 studies
Year 1993: Found 246 studies
Year 1994: Found 248 studies
Year 1995: Found 413 studies
Year 1996: Found 534 studies
Year 1997: Found 691 studies
Year 1998: Found 1000 studies

In [114]:
print(final_df)

       NCT Number                                        Study Title  \
0     NCT00005121                             Framingham Heart Study
1     NCT02833129  The Effects of Playing High School Football on...
2     NCT00005122                               Evans County Studies
3     NCT05537194  Effects of Dihydropyridine Calcium Channel Inh...
4     NCT00005123                             Honolulu Heart Program
...           ...                                                ...
3078  NCT00005556  Retention of Bone Marrow Donors in a National ...
3079  NCT00003445  Docetaxel in Treating Patients With Advanced C...
3080  NCT00002873  Radiation Therapy in Treating Women With Stage...
3081  NCT00003056  Prevention of Graft-Versus-Host Disease in Pat...
3082  NCT00003072  Combination Chemotherapy in Treating Patients ...

     Study Status                                      Brief Summary  \
0       COMPLETED  The Framingham Heart Study was initiated to st...
1       COMPLETED  The purpose of this study is to assess the eff...
2       COMPLETED  To conduct surveillance of cardiovascular morb...
3       COMPLETED  Due to their effects on hypoxic pulmonary vaso...
4       COMPLETED  To investigate coronary heart disease and stro...
...           ...                                                ...
3078    COMPLETED  To identify factors that affected the National...
3079    COMPLETED  RATIONALE: Drugs used in chemotherapy use diff...
3080    COMPLETED  RATIONALE: Radiation therapy may kill any tumo...
3081   TERMINATED  RATIONALE: Peripheral stem cell transplantatio...
3082    COMPLETED  RATIONALE: Drugs used in chemotherapy use diff...

                                             Conditions  \
0     Cardiovascular Diseases|Heart Diseases|Coronar...
1     Memory Impairment|Executive Dysfunction|Depres...
2     Cardiovascular Diseases|Heart Diseases|Myocard...
3                                               Hypoxia
4     Cardiovascular Diseases|Coronary Disease|Cereb...
...                                                 ...
3078          Bone Marrow Transplantation|Blood Disease
3079                                    Cervical Cancer
3080                                      Breast Cancer
3081        Leukemia|Lymphoma|Graft Versus Host Disease
3082           Lung Cancer|Neurotoxicity|Ovarian Cancer

                               Primary Outcome Measures  \
0
1     Summary score of psychological distress/depres...
2
3     association between dihydropyridine CCI or ura...
4
...                                                 ...
3078
3079
3080
3081  Time to neutrophil engraftment, Month 1, post-...
3082

                                                Sponsor  \
0     National Heart, Lung, and Blood Institute (NHLBI)
1                            University of Pennsylvania
2     National Heart, Lung, and Blood Institute (NHLBI)
3                             University Hospital, Caen
4     National Heart, Lung, and Blood Institute (NHLBI)
...                                                 ...
3078  National Heart, Lung, and Blood Institute (NHLBI)
3079               Grupo Oncologico Cooperativo del Sur
3080                   Radiation Therapy Oncology Group
3081                          Baxalta now part of Shire
3082            University of California, San Francisco

                                          Collaborators     Sex  \
0                                                           ALL
1     University of Wisconsin, Madison|Moss Rehabili...    MALE
2                                                          MALE
3                                                           ALL
4                                                          MALE
...                                                 ...     ...
3078                                                       MALE
3079                                                     FEMALE
3080                    National Cancer Institute (NCI)  FEMALE
3081                                                        ALL
3082                                                        ALL

                            Age Enrollment Funder Type      Study Type  \
0     CHILD, ADULT, OLDER_ADULT                    NIH   OBSERVATIONAL
1     CHILD, ADULT, OLDER_ADULT       3904       OTHER   OBSERVATIONAL
2     CHILD, ADULT, OLDER_ADULT                    NIH   OBSERVATIONAL
3     CHILD, ADULT, OLDER_ADULT   32000000       OTHER   OBSERVATIONAL
4     CHILD, ADULT, OLDER_ADULT                    NIH   OBSERVATIONAL
...                         ...        ...         ...             ...
3078  CHILD, ADULT, OLDER_ADULT                    NIH   OBSERVATIONAL
3079  CHILD, ADULT, OLDER_ADULT                  OTHER  INTERVENTIONAL
3080  CHILD, ADULT, OLDER_ADULT                NETWORK  INTERVENTIONAL
3081                      ADULT        105    INDUSTRY  INTERVENTIONAL
3082         ADULT, OLDER_ADULT         80       OTHER  INTERVENTIONAL

      Start Date Completion Date
0        1948-07         2008-09
1        1957-01         2011-12
2        1958-07         1995-08
3     1963-01-01      2022-08-14
4        1965-07         2002-09
...          ...             ...
3078     1997-05         2003-04
3079     1997-12         2004-04
3080     1997-05
3081  1997-04-01      2003-06-01
3082     1997-05         1998-10

[3083 rows x 15 columns]

In [ ]:
##################################################################################################################################################################
# SECOND BLOCK: 1999 - 2007

In [121]:
search_terms = "(Abdominal cerclage OR Abnormal pap smears OR Abnormal uterine bleeding OR Alzheimer's disease OR Amenorrhea OR Amniocentesis OR Arthritis OR Asthma OR Bacterial vaginosis OR Bleeding disorders OR Breast cancer OR Cancers OR Celiac disease OR Cervical cancer OR Cervical insufficiency OR Cervicitis OR Cesarean section (C-section) OR Chorionic villus sampling OR Colposcopy OR Congenital abnormalities OR Continence OR Contraception (birth control) OR Cystoscopy OR Depression and anxiety OR Dilation and curettage (D and C) OR Dysmenorrhea OR Endometrial ablation OR Endometrial biopsy OR Endometrial cancer OR Endometriosis OR Epilepsy OR Family planning OR Female genital cutting OR Fertility preservation OR Fibroma OR Gallstone disease OR Genetic conditions OR Gentle cesarean section OR Gestational diabetes OR Gestational trophoblastic disease OR Graves' disease OR Gynecologic cancer OR Gynecologic specialty care OR Gynecologic well-woman care OR Gynecological surgery OR Heart disease OR Heavy menstrual cycles OR High-risk pregnancy OR HIV OR HPV OR In-vitro fertilization OR Infertility OR Integrative medicine OR Interstitial cystitis OR Irritable bowel syndrome (IBS) OR Laparoscopic hysterectomy OR Laparoscopy OR Loop electrosurgical excision procedure (LEEP) OR Lupus OR Menopause OR Menorrhagia OR Menstrual conditions OR Miscarriage OR Morning sickness OR Multiple sclerosis OR Myomectomy OR Osteoarthritis OR Osteoporosis OR Ovarian cancer OR Ovarian cysts OR Ovarian fibroma OR Overactive bladder OR Pancreatic cystic neoplasm OR Pap test OR Pelvic inflammatory disease (PID) OR Pelvic organ prolapse OR Pelvic pain OR Pelvic ultrasound OR Perimenopause OR Placenta accreta OR Placenta previa OR Polycystic ovary syndrome (PCOS) OR Postpartum depression OR Preconception planning OR Pregnancy OR Pregnancy complications OR Pregnancy, first trimester OR Pregnancy, multiples OR Pregnancy, second trimester OR Pregnancy, third trimester OR Premenstrual dysphoric disorder (PMDD) OR Premenstrual syndrome (PMS) OR Prenatal care OR Prenatal genetic screening OR Preterm birth OR Primary care for women OR Recurrent pregnancy loss OR Rheumatoid arthritis OR Robotic hysterectomy OR Robotic myomectomy OR Sexually transmitted diseases (STDs) OR Sleep disorders OR Small vessel disease OR Sports injuries OR STIs OR Stress urinary incontinence OR Stroke OR Thyroid disease OR Transgender care OR Tubal ligation OR Turner syndrome OR Type I autoimmune hepatitis OR Ultrasound OR Urinary incontinence OR Urinary tract infections (UTIs) OR Uterine and vaginal prolapse OR Uterine fibroids OR Vaginal birth after cesarean section OR Vaginal cancer OR Vaginitis OR Vulvar cancer OR Vulvar dysplasia OR Vulvitis OR Yeast infection)"
target_fields =["NCT Number", "Study Title", "Study Status", "Brief Summary", "Conditions", "Primary Outcome Measures",
                "Sponsor", "Collaborators", "Sex", "Age", "Enrollment", "Study Type", "Funder Type", "Start Date", "Completion Date"]

dfs_list2 = []

for year in range(1999, 2008):
    for month in range(1, 13):
        last_day = calendar.monthrange(year, month)[1]
        start_str2 = f"{year}-{month:02d}-01" # {month:02d} formats the month to MM because clinical trials is strict
        end_str2 = f"{year}-{month:02d}-{last_day:02d}"
        
        month_query = f"{search_terms} AND AREA[StartDate]RANGE[{start_str2}, {end_str2}]"
        
        
        try:
            fields2 = ct.get_study_fields(search_expr=month_query, fields=target_fields, max_studies=1000, fmt="csv")
            
            if fields2 and len(fields2) > 1:
                df2 = pd.DataFrame.from_records(fields2[1:], columns=fields2[0])
                dfs_list2.append(df2)
                
                studies_number2 = len(df2)
                print(f"{year}-{month:02d}: Found {studies_number2} studies")
                
            else:
                print(f"{year}-{month:02d}: No studies found.")
                
        except Exception as e:
            print(f"Error querying Year {year}-{month:02d}: {e}")
            
        time.sleep(3)

if dfs_list2:
    final_df2 = pd.concat(dfs_list2, ignore_index = True)
else:
    print("No data collected")
    final_df2 = pd.DataFrame(columns=target_fields)

1999-01: Found 140 studies
1999-02: Found 77 studies
1999-03: Found 106 studies
1999-04: Found 107 studies
1999-05: Found 82 studies
1999-06: Found 92 studies
1999-07: Found 119 studies
1999-08: Found 118 studies
1999-09: Found 148 studies
1999-10: Found 162 studies
1999-11: Found 103 studies
1999-12: Found 117 studies
2000-01: Found 291 studies
2000-02: Found 128 studies
2000-03: Found 133 studies
2000-04: Found 107 studies
2000-05: Found 142 studies
2000-06: Found 155 studies
2000-07: Found 119 studies
2000-08: Found 163 studies
2000-09: Found 181 studies
2000-10: Found 139 studies
2000-11: Found 114 studies
2000-12: Found 117 studies
2001-01: Found 239 studies
2001-02: Found 153 studies
2001-03: Found 152 studies
2001-04: Found 189 studies
2001-05: Found 152 studies
2001-06: Found 158 studies
2001-07: Found 150 studies
2001-08: Found 172 studies
2001-09: Found 199 studies
2001-10: Found 201 studies
2001-11: Found 176 studies
2001-12: Found 133 studies
2002-01: Found 311 studies
2002-02: Found 177 studies
2002-03: Found 210 studies
2002-04: Found 235 studies
2002-05: Found 200 studies
2002-06: Found 216 studies
2002-07: Found 230 studies
2002-08: Found 193 studies
2002-09: Found 271 studies
2002-10: Found 279 studies
2002-11: Found 214 studies
2002-12: Found 208 studies
2003-01: Found 416 studies
2003-02: Found 248 studies
2003-03: Found 308 studies
2003-04: Found 312 studies
2003-05: Found 264 studies
2003-06: Found 339 studies
2003-07: Found 293 studies
2003-08: Found 261 studies
2003-09: Found 381 studies
2003-10: Found 349 studies
2003-11: Found 276 studies
2003-12: Found 290 studies
2004-01: Found 524 studies
2004-02: Found 326 studies
2004-03: Found 403 studies
2004-04: Found 420 studies
2004-05: Found 355 studies
2004-06: Found 414 studies
2004-07: Found 382 studies
2004-08: Found 351 studies
2004-09: Found 446 studies
2004-10: Found 414 studies
2004-11: Found 384 studies
2004-12: Found 384 studies
2005-01: Found 672 studies
2005-02: Found 329 studies
2005-03: Found 460 studies
2005-04: Found 424 studies
2005-05: Found 456 studies
2005-06: Found 488 studies
2005-07: Found 465 studies
2005-08: Found 430 studies
2005-09: Found 631 studies
2005-10: Found 495 studies
2005-11: Found 489 studies
2005-12: Found 448 studies
2006-01: Found 803 studies
2006-02: Found 524 studies
2006-03: Found 581 studies
2006-04: Found 524 studies
2006-05: Found 618 studies
2006-06: Found 605 studies
2006-07: Found 524 studies
2006-08: Found 539 studies
2006-09: Found 613 studies
2006-10: Found 631 studies
2006-11: Found 593 studies
2006-12: Found 529 studies
2007-01: Found 902 studies
2007-02: Found 548 studies
2007-03: Found 670 studies
2007-04: Found 586 studies
2007-05: Found 648 studies
2007-06: Found 684 studies
2007-07: Found 637 studies
2007-08: Found 638 studies
2007-09: Found 731 studies
2007-10: Found 768 studies
2007-11: Found 663 studies
2007-12: Found 556 studies

In [123]:
print(final_df2)

        NCT Number                                        Study Title  \
0      NCT04308993  Percutaneous Endoscopic Biliary Exploration in...
1      NCT00381511        Deferment of Imaging for Pulmonary Embolism
2      NCT00115271  Antenatal Micronutrient Supplementation and Bi...
3      NCT00003552  Chemotherapy and Peripheral Stem Cell Transpla...
4      NCT03197233  Vitamin A and D Intake in Pregnancy, Infant Su...
...            ...                                                ...
37415  NCT01170091  Safety and Effect of Mirapex(Pramipexole) Tabl...
37416  NCT00572442  Magnetocardiography (MCG) in Asymptomatic Indi...
37417  NCT00782470  Evaluation of the Reasons and Consequences of ...
37418  NCT03414502  Treatment of Rheumatoid Arthritis With DMARDs:...
37419  NCT00592475  A Study to Assess the Safety and Effects of In...

      Study Status                                      Brief Summary  \
0        COMPLETED  Patients with complex biliary stone disease ar...
1        COMPLETED  Background. Management of patients with suspec...
2        COMPLETED  The purpose of this study was to determine the...
3       TERMINATED  RATIONALE: Drugs used in chemotherapy use diff...
4        COMPLETED  The objective of this study is to investigate ...
...            ...                                                ...
37415    COMPLETED  Safety and Effect of Mirapex(Pramipexole) tabl...
37416    WITHDRAWN  The purpose of this research study is to perfo...
37417    COMPLETED  Understanding how often the bleeding events oc...
37418   RECRUITING  Rheumatoid arthritis (RA) is a common disease ...
37419    COMPLETED  To evaluate the safety of IV conivaptan in sta...

                                              Conditions  \
0                                         Biliary Stones
1                                     Pulmonary Embolism
2      Low Birth Weight|Infant Mortality|Pregnancy|Nu...
3                   Stage IV Melanoma|Recurrent Melanoma
4                                     Asthma in Children
...                                                  ...
37415                             Restless Legs Syndrome
37416                                            Healthy
37417    Hematologic Disease|Blood Coagulation Disorders
37418                               Rheumatoid Arthritis
37419                                    Liver Cirrhosis

                                Primary Outcome Measures  \
0      symptoms, success rate of biliary stone cleara...
1      Recurrent venous thromboembolism|major bleedin...
2                  Birth weight|3-month infant mortality
3
4      Child asthma based on dispensed asthma medicat...
...                                                  ...
37415  Number of Reported Adverse Events, If there is...
37416
37417  To evaluate the frequency of all bleeds (spont...
37418  Efficacy of Disease-modifying Antirheumatic Dr...
37419  Change From Baseline in Hepatic Venous Pressur...

                                                 Sponsor  \
0                 Imam Abdulrahman Bin Faisal University
1          Azienda Ospedaliera Universitaria Policlinico
2        Johns Hopkins Bloomberg School of Public Health
3      National Heart, Lung, and Blood Institute (NHLBI)
4                   Norwegian Institute of Public Health
...                                                  ...
37415                               Boehringer Ingelheim
37416                        Cedars-Sinai Medical Center
37417                                              Bayer
37418                             University of Nebraska
37419                         Cumberland Pharmaceuticals

                                           Collaborators     Sex  \
0                                                            ALL
1                                                            ALL
2      United States Agency for International Develop...  FEMALE
3                                                            ALL
4      National Institute of Environmental Health Sci...     ALL
...                                                  ...     ...
37415                                                        ALL
37416                                  CardioMag Imaging     ALL
37417                                                       MALE
37418                                                        ALL
37419                                                        ALL

                      Age Enrollment Funder Type      Study Type  Start Date  \
0      ADULT, OLDER_ADULT         15       OTHER   OBSERVATIONAL  1999-01-01
1      ADULT, OLDER_ADULT        300       OTHER  INTERVENTIONAL     1999-01
2            CHILD, ADULT       5000       OTHER  INTERVENTIONAL     1999-01
3                   ADULT                    NIH  INTERVENTIONAL     1999-01
4                   CHILD      61676   OTHER_GOV   OBSERVATIONAL     1999-01
...                   ...        ...         ...             ...         ...
37415  ADULT, OLDER_ADULT        651    INDUSTRY   OBSERVATIONAL     2007-12
37416  ADULT, OLDER_ADULT         40       OTHER   OBSERVATIONAL     2007-12
37417        CHILD, ADULT         38    INDUSTRY   OBSERVATIONAL     2007-12
37418  ADULT, OLDER_ADULT        400       OTHER  INTERVENTIONAL  2007-12-10
37419  ADULT, OLDER_ADULT         20    INDUSTRY  INTERVENTIONAL     2007-12

      Completion Date
0          2019-08-19
1             2004-04
2             2001-05
3             2002-10
4          2015-06-30
...               ...
37415
37416         2009-12
37417         2010-11
37418         2029-03
37419         2008-11

[37420 rows x 15 columns]

In [ ]:
##################################################################################################################################################################
# THIRD BLOCK: 2008 - 2026

In [124]:
keywords = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer", "Cancers",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)",
            "Chorionic villus sampling", "Colposcopy", "Congenital abnormalities", "Continence", "Contraception (birth control)",
            "Cystoscopy", "Depression and anxiety", "Dilation and curettage (D and C)", "Dysmenorrhea",  "Endometrial ablation",  "Endometrial biopsy",
            "Endometrial cancer", "Endometriosis", "Epilepsy", "Family planning", "Female genital cutting", "Fertility preservation",
            "Fibroma", "Gallstone disease",  "Genetic conditions", "Gentle cesarean section", "Gestational diabetes", "Gestational trophoblastic disease",
            "Graves' disease", "Gynecologic cancer", "Gynecologic specialty care", "Gynecologic well-woman care", "Gynecological surgery",  "Heart disease",
             "Heavy menstrual cycles", "High-risk pregnancy","HIV", "HPV", "In-vitro fertilization", "Infertility", "Integrative medicine", "Interstitial cystitis",
             "Irritable bowel syndrome (IBS)", "Laparoscopic hysterectomy", "Laparoscopy", "Loop electrosurgical excision procedure (LEEP)", "Lupus",
             "Menopause", "Menorrhagia", "Menstrual conditions", "Miscarriage", "Morning sickness", "Multiple sclerosis", "Myomectomy", "Osteoarthritis", "Osteoporosis",
             "Ovarian cancer", "Ovarian cysts", "Ovarian fibroma", "Overactive bladder", "Pancreatic cystic neoplasm", "Pap test", "Pelvic inflammatory disease (PID)",
             "Pelvic organ prolapse", "Pelvic pain", "Pelvic ultrasound", "Perimenopause", "Placenta accreta", "Placenta previa", "Polycystic ovary syndrome (PCOS)",
             "Postpartum depression", "Preconception planning", "Pregnancy", "Pregnancy complications", "Pregnancy, first trimester", "Pregnancy, multiples",
             "Pregnancy, second trimester", "Pregnancy, third trimester", "Premenstrual dysphoric disorder (PMDD)", "Premenstrual syndrome (PMS)", "Prenatal care", "Prenatal genetic screening", "Preterm birth",
             "Primary care for women", "Recurrent pregnancy loss", "Rheumatoid arthritis", "Robotic hysterectomy", "Robotic myomectomy", "Sexually transmitted diseases (STDs)", 
             "Sleep disorders", "Small vessel disease", "Sports injuries", "STIs", "Stress urinary incontinence", "Stroke", "Thyroid disease", "Transgender care", "Tubal ligation",
             "Turner syndrome", "Type I autoimmune hepatitis", "Ultrasound", "Urinary incontinence", "Urinary tract infections (UTIs)", "Uterine and vaginal prolapse", "Uterine fibroids",
             "Vaginal birth after cesarean section", "Vaginal cancer", "Vaginitis", "Vulvar cancer", "Vulvar dysplasia", "Vulvitis", "Yeast infection"
]

target_fields =["NCT Number", "Study Title", "Study Status", "Brief Summary", "Conditions", "Primary Outcome Measures",
                "Sponsor", "Collaborators", "Sex", "Age", "Enrollment", "Study Type", "Funder Type", "Start Date", "Completion Date"]

dfs_list3 = []

for year in range(2008, 2027):
    for month in range(1, 13):
        last_day = calendar.monthrange(year, month)[1]
        start_str3 = f"{year}-{month:02d}-01" 
        end_str3 = f"{year}-{month:02d}-{last_day:02d}"

        # Look through keywords list
        for keyword in keywords:
            keyword_month_query = f"{keyword} AND AREA[StartDate]RANGE[{start_str3}, {end_str3}]"

            try:
                fields3 = ct.get_study_fields(search_expr=keyword_month_query, fields=target_fields, max_studies=1000, fmt="csv")

                if fields3 and len(fields3) > 1:
                    df3 = pd.DataFrame.from_records(fields3[1:], columns = fields3[0])
                    dfs_list3.append(df3)

                    studies_number3 = len(df3)
                    print(f"{year}-{month:02d}: Found {studies_number3} studies for keyword '{keyword}'")

            except Exception as e:
                print(f" Error for keywrod '{keyword}' in {year}-{month:02d}: {e}")

            time.sleep(3)

if dfs_list3:
    final_df3 = pd.concat(dfs_list, ignore_index = True)
else:
    print("No data collected")
    final_df3 = pd.DataFrame(columns=target_fields)

2008-01: Found 4 studies for keyword 'Abnormal uterine bleeding'
2008-01: Found 17 studies for keyword 'Alzheimer's disease'
2008-01: Found 2 studies for keyword 'Amenorrhea'
2008-01: Found 46 studies for keyword 'Arthritis'
2008-01: Found 36 studies for keyword 'Asthma'
2008-01: Found 1 studies for keyword 'Bacterial vaginosis'
2008-01: Found 57 studies for keyword 'Bleeding disorders'
2008-01: Found 55 studies for keyword 'Breast cancer'
2008-01: Found 373 studies for keyword 'Cancers'
2008-01: Found 1 studies for keyword 'Celiac disease'
2008-01: Found 36 studies for keyword 'Cervical cancer'
2008-01: Found 1 studies for keyword 'Cervical insufficiency'
2008-01: Found 4 studies for keyword 'Cesarean section (C-section)'
2008-01: Found 1 studies for keyword 'Colposcopy'
2008-01: Found 120 studies for keyword 'Congenital abnormalities'
2008-01: Found 2 studies for keyword 'Continence'
2008-01: Found 8 studies for keyword 'Contraception (birth control)'
2008-01: Found 1 studies for keyword 'Cystoscopy'
2008-01: Found 33 studies for keyword 'Depression and anxiety'
2008-01: Found 1 studies for keyword 'Dilation and curettage (D and C)'
2008-01: Found 3 studies for keyword 'Dysmenorrhea'
2008-01: Found 1 studies for keyword 'Endometrial ablation'
2008-01: Found 2 studies for keyword 'Endometrial biopsy'
2008-01: Found 3 studies for keyword 'Endometrial cancer'
2008-01: Found 9 studies for keyword 'Epilepsy'
2008-01: Found 8 studies for keyword 'Family planning'
2008-01: Found 1 studies for keyword 'Fibroma'
2008-01: Found 3 studies for keyword 'Gallstone disease'
2008-01: Found 31 studies for keyword 'Genetic conditions'
2008-01: Found 4 studies for keyword 'Gestational diabetes'
2008-01: Found 1 studies for keyword 'Graves' disease'
2008-01: Found 6 studies for keyword 'Gynecologic cancer'
2008-01: Found 5 studies for keyword 'Gynecological surgery'
2008-01: Found 211 studies for keyword 'Heart disease'
2008-01: Found 30 studies for keyword 'High-risk pregnancy'
2008-01: Found 26 studies for keyword 'HIV'
2008-01: Found 4 studies for keyword 'HPV'
2008-01: Found 9 studies for keyword 'In-vitro fertilization'
2008-01: Found 25 studies for keyword 'Infertility'
2008-01: Found 3 studies for keyword 'Integrative medicine'
2008-01: Found 1 studies for keyword 'Irritable bowel syndrome (IBS)'
2008-01: Found 2 studies for keyword 'Laparoscopic hysterectomy'
2008-01: Found 28 studies for keyword 'Laparoscopy'
2008-01: Found 1 studies for keyword 'Loop electrosurgical excision procedure (LEEP)'
2008-01: Found 4 studies for keyword 'Lupus'
2008-01: Found 16 studies for keyword 'Menopause'
2008-01: Found 2 studies for keyword 'Menorrhagia'
2008-01: Found 6 studies for keyword 'Menstrual conditions'
2008-01: Found 1 studies for keyword 'Miscarriage'
2008-01: Found 3 studies for keyword 'Morning sickness'
2008-01: Found 8 studies for keyword 'Multiple sclerosis'
2008-01: Found 3 studies for keyword 'Myomectomy'
2008-01: Found 24 studies for keyword 'Osteoarthritis'
2008-01: Found 14 studies for keyword 'Osteoporosis'
2008-01: Found 17 studies for keyword 'Ovarian cancer'
2008-01: Found 6 studies for keyword 'Ovarian cysts'
2008-01: Found 2 studies for keyword 'Overactive bladder'
2008-01: Found 1 studies for keyword 'Pancreatic cystic neoplasm'
2008-01: Found 3 studies for keyword 'Pap test'
2008-01: Found 2 studies for keyword 'Pelvic inflammatory disease (PID)'
2008-01: Found 3 studies for keyword 'Pelvic organ prolapse'
2008-01: Found 5 studies for keyword 'Pelvic pain'
2008-01: Found 2 studies for keyword 'Pelvic ultrasound'
2008-01: Found 1 studies for keyword 'Perimenopause'
2008-01: Found 1 studies for keyword 'Placenta previa'
2008-01: Found 8 studies for keyword 'Polycystic ovary syndrome (PCOS)'
2008-01: Found 130 studies for keyword 'Pregnancy'
2008-01: Found 104 studies for keyword 'Pregnancy complications'
2008-01: Found 5 studies for keyword 'Pregnancy, first trimester'
2008-01: Found 7 studies for keyword 'Prenatal care'
2008-01: Found 18 studies for keyword 'Preterm birth'
2008-01: Found 14 studies for keyword 'Primary care for women'
2008-01: Found 1 studies for keyword 'Recurrent pregnancy loss'
2008-01: Found 13 studies for keyword 'Rheumatoid arthritis'
2008-01: Found 1 studies for keyword 'Robotic hysterectomy'
2008-01: Found 24 studies for keyword 'Sexually transmitted diseases (STDs)'
2008-01: Found 60 studies for keyword 'Sleep disorders'
2008-01: Found 40 studies for keyword 'Small vessel disease'
2008-01: Found 5 studies for keyword 'Sports injuries'
2008-01: Found 24 studies for keyword 'STIs'
2008-01: Found 2 studies for keyword 'Stress urinary incontinence'
2008-01: Found 61 studies for keyword 'Stroke'
2008-01: Found 11 studies for keyword 'Thyroid disease'
2008-01: Found 1 studies for keyword 'Turner syndrome'
2008-01: Found 61 studies for keyword 'Ultrasound'
2008-01: Found 4 studies for keyword 'Urinary incontinence'
2008-01: Found 4 studies for keyword 'Urinary tract infections (UTIs)'
2008-01: Found 1 studies for keyword 'Uterine and vaginal prolapse'
2008-01: Found 2 studies for keyword 'Uterine fibroids'
2008-01: Found 7 studies for keyword 'Vaginal cancer'
2008-01: Found 2 studies for keyword 'Vaginitis'
2008-01: Found 1 studies for keyword 'Vulvitis'
2008-01: Found 3 studies for keyword 'Yeast infection'
2008-02: Found 1 studies for keyword 'Abnormal pap smears'
2008-02: Found 13 studies for keyword 'Alzheimer's disease'
2008-02: Found 1 studies for keyword 'Amenorrhea'
2008-02: Found 15 studies for keyword 'Arthritis'
2008-02: Found 20 studies for keyword 'Asthma'
2008-02: Found 1 studies for keyword 'Bacterial vaginosis'
2008-02: Found 33 studies for keyword 'Bleeding disorders'
2008-02: Found 31 studies for keyword 'Breast cancer'
2008-02: Found 286 studies for keyword 'Cancers'
2008-02: Found 3 studies for keyword 'Celiac disease'
2008-02: Found 27 studies for keyword 'Cervical cancer'
2008-02: Found 5 studies for keyword 'Cesarean section (C-section)'
2008-02: Found 1 studies for keyword 'Colposcopy'
2008-02: Found 60 studies for keyword 'Congenital abnormalities'
2008-02: Found 2 studies for keyword 'Continence'
2008-02: Found 2 studies for keyword 'Contraception (birth control)'
2008-02: Found 3 studies for keyword 'Cystoscopy'
2008-02: Found 18 studies for keyword 'Depression and anxiety'
2008-02: Found 1 studies for keyword 'Dysmenorrhea'
2008-02: Found 1 studies for keyword 'Endometrial biopsy'
2008-02: Found 4 studies for keyword 'Endometrial cancer'
2008-02: Found 2 studies for keyword 'Endometriosis'
2008-02: Found 8 studies for keyword 'Epilepsy'
2008-02: Found 7 studies for keyword 'Family planning'
2008-02: Found 1 studies for keyword 'Gallstone disease'
2008-02: Found 8 studies for keyword 'Genetic conditions'
2008-02: Found 4 studies for keyword 'Gestational diabetes'
2008-02: Found 5 studies for keyword 'Gynecologic cancer'
2008-02: Found 5 studies for keyword 'Gynecological surgery'
2008-02: Found 117 studies for keyword 'Heart disease'
2008-02: Found 17 studies for keyword 'High-risk pregnancy'
2008-02: Found 29 studies for keyword 'HIV'
2008-02: Found 6 studies for keyword 'HPV'
2008-02: Found 4 studies for keyword 'In-vitro fertilization'
2008-02: Found 13 studies for keyword 'Infertility'
2008-02: Found 5 studies for keyword 'Integrative medicine'
2008-02: Found 4 studies for keyword 'Irritable bowel syndrome (IBS)'
2008-02: Found 8 studies for keyword 'Laparoscopy'
2008-02: Found 1 studies for keyword 'Loop electrosurgical excision procedure (LEEP)'
2008-02: Found 2 studies for keyword 'Lupus'
2008-02: Found 5 studies for keyword 'Menopause'
2008-02: Found 1 studies for keyword 'Menorrhagia'
2008-02: Found 4 studies for keyword 'Menstrual conditions'
2008-02: Found 1 studies for keyword 'Miscarriage'
2008-02: Found 1 studies for keyword 'Morning sickness'
2008-02: Found 14 studies for keyword 'Multiple sclerosis'
2008-02: Found 1 studies for keyword 'Myomectomy'
2008-02: Found 6 studies for keyword 'Osteoarthritis'
2008-02: Found 9 studies for keyword 'Osteoporosis'
2008-02: Found 7 studies for keyword 'Ovarian cancer'
2008-02: Found 3 studies for keyword 'Ovarian cysts'
2008-02: Found 4 studies for keyword 'Overactive bladder'
2008-02: Found 5 studies for keyword 'Pap test'
2008-02: Found 1 studies for keyword 'Pelvic inflammatory disease (PID)'
2008-02: Found 2 studies for keyword 'Pelvic organ prolapse'
2008-02: Found 5 studies for keyword 'Pelvic pain'
2008-02: Found 5 studies for keyword 'Polycystic ovary syndrome (PCOS)'
2008-02: Found 2 studies for keyword 'Postpartum depression'
2008-02: Found 109 studies for keyword 'Pregnancy'
2008-02: Found 89 studies for keyword 'Pregnancy complications'
2008-02: Found 1 studies for keyword 'Pregnancy, first trimester'
2008-02: Found 2 studies for keyword 'Pregnancy, second trimester'
2008-02: Found 3 studies for keyword 'Pregnancy, third trimester'
2008-02: Found 2 studies for keyword 'Premenstrual syndrome (PMS)'
2008-02: Found 2 studies for keyword 'Prenatal care'
2008-02: Found 4 studies for keyword 'Preterm birth'
2008-02: Found 7 studies for keyword 'Primary care for women'
2008-02: Found 1 studies for keyword 'Recurrent pregnancy loss'
2008-02: Found 7 studies for keyword 'Rheumatoid arthritis'
2008-02: Found 26 studies for keyword 'Sexually transmitted diseases (STDs)'
2008-02: Found 42 studies for keyword 'Sleep disorders'
2008-02: Found 15 studies for keyword 'Small vessel disease'
2008-02: Found 2 studies for keyword 'Sports injuries'
2008-02: Found 26 studies for keyword 'STIs'
2008-02: Found 5 studies for keyword 'Stress urinary incontinence'
2008-02: Found 33 studies for keyword 'Stroke'
2008-02: Found 9 studies for keyword 'Thyroid disease'
2008-02: Found 1 studies for keyword 'Transgender care'
2008-02: Found 25 studies for keyword 'Ultrasound'
2008-02: Found 10 studies for keyword 'Urinary incontinence'
2008-02: Found 7 studies for keyword 'Urinary tract infections (UTIs)'
2008-02: Found 1 studies for keyword 'Uterine and vaginal prolapse'
2008-02: Found 3 studies for keyword 'Vaginal cancer'
2008-02: Found 2 studies for keyword 'Vaginitis'
2008-02: Found 1 studies for keyword 'Vulvitis'
2008-02: Found 2 studies for keyword 'Yeast infection'
2008-03: Found 8 studies for keyword 'Alzheimer's disease'
2008-03: Found 1 studies for keyword 'Amenorrhea'
2008-03: Found 32 studies for keyword 'Arthritis'
2008-03: Found 24 studies for keyword 'Asthma'
2008-03: Found 40 studies for keyword 'Bleeding disorders'
2008-03: Found 51 studies for keyword 'Breast cancer'
2008-03: Found 291 studies for keyword 'Cancers'
2008-03: Found 3 studies for keyword 'Celiac disease'
2008-03: Found 29 studies for keyword 'Cervical cancer'
2008-03: Found 1 studies for keyword 'Cervical insufficiency'
2008-03: Found 1 studies for keyword 'Cesarean section (C-section)'
2008-03: Found 89 studies for keyword 'Congenital abnormalities'
2008-03: Found 1 studies for keyword 'Continence'
2008-03: Found 3 studies for keyword 'Contraception (birth control)'
2008-03: Found 22 studies for keyword 'Depression and anxiety'
2008-03: Found 1 studies for keyword 'Dilation and curettage (D and C)'
2008-03: Found 1 studies for keyword 'Dysmenorrhea'
2008-03: Found 4 studies for keyword 'Endometrial cancer'
2008-03: Found 2 studies for keyword 'Endometriosis'
2008-03: Found 3 studies for keyword 'Epilepsy'
2008-03: Found 6 studies for keyword 'Family planning'
2008-03: Found 3 studies for keyword 'Gallstone disease'
2008-03: Found 19 studies for keyword 'Genetic conditions'
2008-03: Found 1 studies for keyword 'Gestational diabetes'
2008-03: Found 1 studies for keyword 'Gestational trophoblastic disease'
2008-03: Found 1 studies for keyword 'Graves' disease'
2008-03: Found 3 studies for keyword 'Gynecologic cancer'
2008-03: Found 1 studies for keyword 'Gynecologic specialty care'
2008-03: Found 2 studies for keyword 'Gynecologic well-woman care'
2008-03: Found 4 studies for keyword 'Gynecological surgery'
2008-03: Found 135 studies for keyword 'Heart disease'
2008-03: Found 14 studies for keyword 'High-risk pregnancy'
2008-03: Found 30 studies for keyword 'HIV'
2008-03: Found 7 studies for keyword 'HPV'
2008-03: Found 12 studies for keyword 'Infertility'
2008-03: Found 4 studies for keyword 'Integrative medicine'
2008-03: Found 1 studies for keyword 'Interstitial cystitis'
2008-03: Found 9 studies for keyword 'Laparoscopy'
2008-03: Found 1 studies for keyword 'Lupus'
2008-03: Found 7 studies for keyword 'Menopause'
2008-03: Found 2 studies for keyword 'Menorrhagia'
2008-03: Found 2 studies for keyword 'Menstrual conditions'
2008-03: Found 2 studies for keyword 'Miscarriage'
2008-03: Found 1 studies for keyword 'Morning sickness'
2008-03: Found 8 studies for keyword 'Multiple sclerosis'
2008-03: Found 13 studies for keyword 'Osteoarthritis'
2008-03: Found 6 studies for keyword 'Osteoporosis'
2008-03: Found 17 studies for keyword 'Ovarian cancer'
2008-03: Found 3 studies for keyword 'Ovarian cysts'
2008-03: Found 3 studies for keyword 'Overactive bladder'
2008-03: Found 3 studies for keyword 'Pap test'
2008-03: Found 3 studies for keyword 'Pelvic pain'
2008-03: Found 1 studies for keyword 'Pelvic ultrasound'
2008-03: Found 1 studies for keyword 'Placenta previa'
2008-03: Found 3 studies for keyword 'Polycystic ovary syndrome (PCOS)'
2008-03: Found 2 studies for keyword 'Postpartum depression'
2008-03: Found 84 studies for keyword 'Pregnancy'
2008-03: Found 74 studies for keyword 'Pregnancy complications'
2008-03: Found 2 studies for keyword 'Pregnancy, first trimester'
2008-03: Found 1 studies for keyword 'Pregnancy, second trimester'
2008-03: Found 6 studies for keyword 'Prenatal care'
2008-03: Found 16 studies for keyword 'Preterm birth'
2008-03: Found 4 studies for keyword 'Primary care for women'
2008-03: Found 1 studies for keyword 'Recurrent pregnancy loss'
2008-03: Found 13 studies for keyword 'Rheumatoid arthritis'
2008-03: Found 29 studies for keyword 'Sexually transmitted diseases (STDs)'
2008-03: Found 45 studies for keyword 'Sleep disorders'
2008-03: Found 28 studies for keyword 'Small vessel disease'
2008-03: Found 29 studies for keyword 'STIs'
2008-03: Found 25 studies for keyword 'Stroke'
2008-03: Found 8 studies for keyword 'Thyroid disease'
2008-03: Found 39 studies for keyword 'Ultrasound'
2008-03: Found 8 studies for keyword 'Urinary incontinence'
2008-03: Found 1 studies for keyword 'Urinary tract infections (UTIs)'
2008-03: Found 1 studies for keyword 'Vaginal birth after cesarean section'
2008-03: Found 1 studies for keyword 'Vaginal cancer'
2008-03: Found 1 studies for keyword 'Yeast infection'
2008-04: Found 18 studies for keyword 'Alzheimer's disease'
2008-04: Found 28 studies for keyword 'Arthritis'
2008-04: Found 21 studies for keyword 'Asthma'
2008-04: Found 1 studies for keyword 'Bacterial vaginosis'
2008-04: Found 36 studies for keyword 'Bleeding disorders'
2008-04: Found 51 studies for keyword 'Breast cancer'
2008-04: Found 293 studies for keyword 'Cancers'
2008-04: Found 1 studies for keyword 'Celiac disease'
2008-04: Found 26 studies for keyword 'Cervical cancer'
2008-04: Found 4 studies for keyword 'Cesarean section (C-section)'
2008-04: Found 84 studies for keyword 'Congenital abnormalities'
2008-04: Found 2 studies for keyword 'Continence'
2008-04: Found 4 studies for keyword 'Contraception (birth control)'
2008-04: Found 38 studies for keyword 'Depression and anxiety'
2008-04: Found 2 studies for keyword 'Dilation and curettage (D and C)'
2008-04: Found 4 studies for keyword 'Endometrial cancer'
2008-04: Found 1 studies for keyword 'Endometriosis'
2008-04: Found 10 studies for keyword 'Epilepsy'
2008-04: Found 6 studies for keyword 'Family planning'
2008-04: Found 1 studies for keyword 'Gallstone disease'
2008-04: Found 15 studies for keyword 'Genetic conditions'
2008-04: Found 4 studies for keyword 'Gestational diabetes'
2008-04: Found 1 studies for keyword 'Graves' disease'
2008-04: Found 7 studies for keyword 'Gynecologic cancer'
2008-04: Found 3 studies for keyword 'Gynecological surgery'
2008-04: Found 150 studies for keyword 'Heart disease'
2008-04: Found 10 studies for keyword 'High-risk pregnancy'
2008-04: Found 31 studies for keyword 'HIV'
2008-04: Found 5 studies for keyword 'HPV'
2008-04: Found 3 studies for keyword 'In-vitro fertilization'
2008-04: Found 19 studies for keyword 'Infertility'
2008-04: Found 3 studies for keyword 'Integrative medicine'
2008-04: Found 1 studies for keyword 'Interstitial cystitis'
2008-04: Found 2 studies for keyword 'Irritable bowel syndrome (IBS)'
2008-04: Found 1 studies for keyword 'Laparoscopic hysterectomy'
2008-04: Found 12 studies for keyword 'Laparoscopy'
2008-04: Found 2 studies for keyword 'Lupus'
2008-04: Found 10 studies for keyword 'Menopause'
2008-04: Found 1 studies for keyword 'Menorrhagia'
2008-04: Found 3 studies for keyword 'Menstrual conditions'
2008-04: Found 2 studies for keyword 'Miscarriage'
2008-04: Found 7 studies for keyword 'Multiple sclerosis'
2008-04: Found 17 studies for keyword 'Osteoarthritis'
2008-04: Found 8 studies for keyword 'Osteoporosis'
2008-04: Found 10 studies for keyword 'Ovarian cancer'
2008-04: Found 3 studies for keyword 'Ovarian cysts'
2008-04: Found 5 studies for keyword 'Overactive bladder'
2008-04: Found 1 studies for keyword 'Pap test'
2008-04: Found 1 studies for keyword 'Pelvic inflammatory disease (PID)'
2008-04: Found 2 studies for keyword 'Pelvic organ prolapse'
2008-04: Found 2 studies for keyword 'Pelvic pain'
2008-04: Found 2 studies for keyword 'Polycystic ovary syndrome (PCOS)'
2008-04: Found 4 studies for keyword 'Postpartum depression'
2008-04: Found 103 studies for keyword 'Pregnancy'
2008-04: Found 84 studies for keyword 'Pregnancy complications'
2008-04: Found 1 studies for keyword 'Pregnancy, second trimester'
2008-04: Found 1 studies for keyword 'Pregnancy, third trimester'
2008-04: Found 1 studies for keyword 'Premenstrual dysphoric disorder (PMDD)'
2008-04: Found 3 studies for keyword 'Prenatal care'
2008-04: Found 9 studies for keyword 'Preterm birth'
2008-04: Found 13 studies for keyword 'Primary care for women'
2008-04: Found 1 studies for keyword 'Recurrent pregnancy loss'
2008-04: Found 11 studies for keyword 'Rheumatoid arthritis'
2008-04: Found 29 studies for keyword 'Sexually transmitted diseases (STDs)'
2008-04: Found 49 studies for keyword 'Sleep disorders'
2008-04: Found 28 studies for keyword 'Small vessel disease'
2008-04: Found 1 studies for keyword 'Sports injuries'
2008-04: Found 29 studies for keyword 'STIs'
2008-04: Found 2 studies for keyword 'Stress urinary incontinence'
2008-04: Found 32 studies for keyword 'Stroke'
2008-04: Found 9 studies for keyword 'Thyroid disease'
2008-04: Found 31 studies for keyword 'Ultrasound'
2008-04: Found 7 studies for keyword 'Urinary incontinence'
2008-04: Found 3 studies for keyword 'Urinary tract infections (UTIs)'
2008-04: Found 1 studies for keyword 'Uterine and vaginal prolapse'
2008-04: Found 1 studies for keyword 'Vaginal birth after cesarean section'
2008-04: Found 2 studies for keyword 'Vaginal cancer'
2008-04: Found 1 studies for keyword 'Vaginitis'
2008-04: Found 2 studies for keyword 'Vulvar cancer'
2008-04: Found 1 studies for keyword 'Yeast infection'
2008-05: Found 7 studies for keyword 'Alzheimer's disease'
2008-05: Found 41 studies for keyword 'Arthritis'
2008-05: Found 24 studies for keyword 'Asthma'
2008-05: Found 36 studies for keyword 'Bleeding disorders'
2008-05: Found 51 studies for keyword 'Breast cancer'
2008-05: Found 274 studies for keyword 'Cancers'
2008-05: Found 2 studies for keyword 'Celiac disease'
2008-05: Found 24 studies for keyword 'Cervical cancer'
2008-05: Found 2 studies for keyword 'Cervical insufficiency'
2008-05: Found 2 studies for keyword 'Cesarean section (C-section)'
2008-05: Found 1 studies for keyword 'Colposcopy'
2008-05: Found 84 studies for keyword 'Congenital abnormalities'

KeyboardInterrupt:

In [126]:
if 'dfs_list3' in locals() and dfs_list3:
    df = pd.concat(dfs_list3, ignore_index = True)

In [127]:
df

,NCT Number,Study Title,Study Status,Brief Summary,Conditions,Primary Outcome Measures,Sponsor,Collaborators,Sex,Age,Enrollment,Funder Type,Study Type,Start Date,Completion Date
0,NCT00591968,Telesonography Adaptation and Use to Improve t...,COMPLETED,The role of teleradiology has far reaching imp...,Ascites|Blunt Abdominal Trauma|Cholelithiasis|...,"Using frequency distribution graphs, the time ...",Edward Via Virginia College of Osteopathic Med...,Virginia Polytechnic Institute and State Unive...,ALL,"CHILD, ADULT, OLDER_ADULT",106,OTHER,INTERVENTIONAL,2008-01,2008-03
1,NCT04222621,Xiamen Registry of Pregnant Women and Offsprin...,UNKNOWN,To improve the health of women and children un...,Pregnant Women|Registries,"Incidence of pre-eclampsia, Maternal systolic ...",West China Hospital,"Xiamen Health and Medical Big Data Center, Xia...",FEMALE,"CHILD, ADULT, OLDER_ADULT",761194,OTHER,OBSERVATIONAL,2008-01,2023-12
2,NCT00524342,IL-11 in Women With Von Willebrand Disease and...,COMPLETED,The purpose of this study is to determine the ...,Von Willebrand Disease,>50% Reduction in PBAC (Pictorial Blood Assess...,Margaret Ragni,University of North Carolina|Wyeth is now a wh...,FEMALE,ADULT,7,OTHER,INTERVENTIONAL,2008-01,2010-12
3,NCT01173965,Endometrial Ablation With Non-hysteroscopic Me...,COMPLETED,Endometrial ablation in women with dysfunction...,Dysfunctional Uterine Bleeding,Amenorrhoea rates one year after intervention,Aristotle University Of Thessaloniki,,FEMALE,ADULT,66,OTHER,INTERVENTIONAL,2008-01,2011-02
4,NCT00571064,The Effectiveness And Safety Of Donepezil Hydr...,COMPLETED,This is a study to determine the effectiveness...,Mild to Severe Alzheimer's Disease,Mini Mental State Examination (MMSE) Total Sco...,Eisai Inc.,Pfizer,ALL,"ADULT, OLDER_ADULT",97,INDUSTRY,INTERVENTIONAL,2008-01,2009-04-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214275,NCT03387202,Laparoscopic Lateral Mesh Suspension for Pelvi...,COMPLETED,This study is aimed to share our clinical expe...,Pelvic Organ Prolapse|Pelvic Floor Prolapse,Change from baseline POP-Q measurements (mm) a...,Fatih Sultan Mehmet Training and Research Hosp...,,FEMALE,"ADULT, OLDER_ADULT",15,OTHER,OBSERVATIONAL,2016-11-01,2018-02-05
214276,NCT03148548,Substudy - Evaluation of Patients With Iliac V...,COMPLETED,Patients with previous diagnosis of iliac vein...,Iliac Vein Thrombosis,Incidence and severity of postthrombotic Syndr...,Cardioangiologisches Centrum Bethanien,,ALL,"ADULT, OLDER_ADULT",85,OTHER,OBSERVATIONAL,2016-11,2018-01
214277,NCT03021954,Platelet Rich Plasma in Levator Ani Muscle Trauma,COMPLETED,Levator trauma (ballooning) often occurs after...,Pelvic Floor Disorders,"Changes of Levator Hiatal Area During Valsava,...",Dr Cipto Mangunkusumo General Hospital,Indonesia University,FEMALE,ADULT,116,OTHER,INTERVENTIONAL,2016-11,2020-01
214278,NCT03144310,To Evaluate the Role of Lung Ultrasonography f...,COMPLETED,Pre op ultrasound with chest auscultation and ...,to Detect the Incidence of Atelectasis,"incidence of atelectasis, incidence of atelect...",Post Graduate Institute of Medical Education a...,,ALL,"ADULT, OLDER_ADULT",32,OTHER,OBSERVATIONAL,2016-11-01,2017-11
214279,NCT02943148,Prediction of Pelvic Adhesions at Repeat Cesar...,COMPLETED,Several methods have been used to predict adhe...,Decrease Maternal Morbidity,Rate of of abdominal adhesions in relation to ...,Assiut University,,FEMALE,"CHILD, ADULT, OLDER_ADULT",300,OTHER,OBSERVATIONAL,2016-11,2018-06

In [128]:
# This will be the final clinicaltrials dataframe with all of the three time blocks together
clinical_trials_data = pd.concat([final_df, final_df2, df], ignore_index = True)

In [129]:
clinical_trials_data

,NCT Number,Study Title,Study Status,Brief Summary,Conditions,Primary Outcome Measures,Sponsor,Collaborators,Sex,Age,Enrollment,Funder Type,Study Type,Start Date,Completion Date
0,NCT00005121,Framingham Heart Study,COMPLETED,The Framingham Heart Study was initiated to st...,Cardiovascular Diseases|Heart Diseases|Coronar...,,"National Heart, Lung, and Blood Institute (NHLBI)",,ALL,"CHILD, ADULT, OLDER_ADULT",,NIH,OBSERVATIONAL,1948-07,2008-09
1,NCT02833129,The Effects of Playing High School Football on...,COMPLETED,The purpose of this study is to assess the eff...,Memory Impairment|Executive Dysfunction|Depres...,Summary score of psychological distress/depres...,University of Pennsylvania,"University of Wisconsin, Madison|Moss Rehabili...",MALE,"CHILD, ADULT, OLDER_ADULT",3904,OTHER,OBSERVATIONAL,1957-01,2011-12
2,NCT00005122,Evans County Studies,COMPLETED,To conduct surveillance of cardiovascular morb...,Cardiovascular Diseases|Heart Diseases|Myocard...,,"National Heart, Lung, and Blood Institute (NHLBI)",,MALE,"CHILD, ADULT, OLDER_ADULT",,NIH,OBSERVATIONAL,1958-07,1995-08
3,NCT05537194,Effects of Dihydropyridine Calcium Channel Inh...,COMPLETED,Due to their effects on hypoxic pulmonary vaso...,Hypoxia,association between dihydropyridine CCI or ura...,"University Hospital, Caen",,ALL,"CHILD, ADULT, OLDER_ADULT",32000000,OTHER,OBSERVATIONAL,1963-01-01,2022-08-14
4,NCT00005123,Honolulu Heart Program,COMPLETED,To investigate coronary heart disease and stro...,Cardiovascular Diseases|Coronary Disease|Cereb...,,"National Heart, Lung, and Blood Institute (NHLBI)",,MALE,"CHILD, ADULT, OLDER_ADULT",,NIH,OBSERVATIONAL,1965-07,2002-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255778,NCT03387202,Laparoscopic Lateral Mesh Suspension for Pelvi...,COMPLETED,This study is aimed to share our clinical expe...,Pelvic Organ Prolapse|Pelvic Floor Prolapse,Change from baseline POP-Q measurements (mm) a...,Fatih Sultan Mehmet Training and Research Hosp...,,FEMALE,"ADULT, OLDER_ADULT",15,OTHER,OBSERVATIONAL,2016-11-01,2018-02-05
255779,NCT03148548,Substudy - Evaluation of Patients With Iliac V...,COMPLETED,Patients with previous diagnosis of iliac vein...,Iliac Vein Thrombosis,Incidence and severity of postthrombotic Syndr...,Cardioangiologisches Centrum Bethanien,,ALL,"ADULT, OLDER_ADULT",85,OTHER,OBSERVATIONAL,2016-11,2018-01
255780,NCT03021954,Platelet Rich Plasma in Levator Ani Muscle Trauma,COMPLETED,Levator trauma (ballooning) often occurs after...,Pelvic Floor Disorders,"Changes of Levator Hiatal Area During Valsava,...",Dr Cipto Mangunkusumo General Hospital,Indonesia University,FEMALE,ADULT,116,OTHER,INTERVENTIONAL,2016-11,2020-01
255781,NCT03144310,To Evaluate the Role of Lung Ultrasonography f...,COMPLETED,Pre op ultrasound with chest auscultation and ...,to Detect the Incidence of Atelectasis,"incidence of atelectasis, incidence of atelect...",Post Graduate Institute of Medical Education a...,,ALL,"ADULT, OLDER_ADULT",32,OTHER,OBSERVATIONAL,2016-11-01,2017-11
255782,NCT02943148,Prediction of Pelvic Adhesions at Repeat Cesar...,COMPLETED,Several methods have been used to predict adhe...,Decrease Maternal Morbidity,Rate of of abdominal adhesions in relation to ...,Assiut University,,FEMALE,"CHILD, ADULT, OLDER_ADULT",300,OTHER,OBSERVATIONAL,2016-11,2018-06

In [135]:
clinical_trials_data.to_csv("clinical_trials_data.csv", index = False)

In [ ]:
##################################################################################################################################################
# RAW DATA TO DB
##################################################################################################################################################

In [133]:
# Connect to the database
conn = psycopg2.connect(
    dbname=os.getenv("DBNAME"),
    user=os.getenv("DBUSER"),
    password=os.getenv("DBPASSWORD"),
    port=os.getenv("DBPORT"),
    host=os.getenv("DBHOST")
)
conn_string=os.getenv("CONNSTRING")

# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DBUSER')}:{os.getenv('DBPASSWORD')}"
    f"@{os.getenv('DBHOST')}:{os.getenv('DBPORT')}/{os.getenv('DBNAME')}"
)

In [ ]:
# Load data to db
# This is for years 1948 - 2016
clinical_trials_data.to_sql("clincial_trials", engine, if_exists="append", index=False, method="multi", chunksize=1000)

255783